#spring.datasource.url=jdbc:postgresql://localhost:5432/spring_app
#spring.datasource.username=postgres
#spring.datasource.password=fox13
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Google
#security.oauth2.client.client-id=378243158836-kad60m0oh2s54q1icfe250eorj140t1g.apps.googleusercontent.com
#security.oauth2.client.client-secret=${secret}
#security.oauth2.client.client-authentication-scheme=form
#security.oauth2.client.scope=openid,email,profile
#security.oauth2.client.access-token-uri=https://www.googleapis.com/oauth2/v4/token
#security.oauth2.client.user-authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#security.oauth2.resource.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#security.oauth2.resource.prefer-token-info=true

# Facebook
#security.oauth2.client.client-id=611805652654964
#security.oauth2.client.client-secret=${secret2}
#security.oauth2.client.access-token-uri=https://graph.facebook.com/oauth/access_token
#security.oauth2.client.user-authorization-uri=https://www.facebook.com/dialog/oauth
#security.oauth2.client.token-name=oauth_token
#security.oauth2.client.client-authentication-scheme=form
#security.oauth2.client.authentication-scheme=query
#security.oauth2.client.scope=email,user_gender
#security.oauth2.resource.user-info-uri=https://graph.facebook.com/me
#security.oauth2.resource.prefer-token-info=true

spring:
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: fox13
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

security:
  oauth2:
    client:
      client-id: 378243158836-kad60m0oh2s54q1icfe250eorj140t1g.apps.googleusercontent.com
      client-secret: ${secret}
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      client-authentication-scheme: form
      scope: openid,email,profile
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true
